version: "3"
services:
   downloader:
      build: ./downloader
      volumes:
         - wca_db:/database
         - wca_db_export:/downloads
         - wca_images:/images
   db:
      image: mysql
      ports:
         - '3306:3306'
      environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
         - MYSQL_DATABASE=${MYSQL_DATABASE}
      volumes:
         - wca_db:/var/lib/mysql
         - wca_db_export:/docker-entrypoint-initdb.d
      depends_on:
         downloader:
            condition: service_completed_successfully
      healthcheck:
         test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
         interval: 3s
         timeout: 3s
         retries: 100
   image-creator:
      build: ./image-creator
      environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
         - MYSQL_DATABASE=${MYSQL_DATABASE}
      depends_on:
         db:
            condition: service_healthy
      volumes:
         - wca_db:/var/lib/mysql
         - wca_images:/images
         #- ./docs/assets:/tmp/cache
   upload:
      build: ./upload
      volumes:
         - wca_images:/images
      environment:
         - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      depends_on:
         image-creator:
            condition: service_completed_successfully
      profiles:
         - upload
   db_gui:
      image: phpmyadmin
      environment:
         - PMA_HOST=db
         - PMA_USER=root
         - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      ports:
         - '6080:80'
      depends_on:
         db:
            condition: service_healthy
      profiles:
         - debug
volumes:
   wca_db_export:
   wca_db:
   wca_images:
